// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using NodaTime.Text;

namespace Fatturazione.Models;

public partial class FatturazioneDbContext : DbContext
{
    public FatturazioneDbContext(DbContextOptions<FatturazioneDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<BaArtkey005> BaArtkey005s { get; set; }

    public virtual DbSet<BaDocume005> BaDocume005s { get; set; }

    public virtual DbSet<BaDocumeM005> BaDocumeM005s { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        var instantConverter = new ValueConverter<Instant, DateTime>(
            v => v.ToDateTimeUtc(),
            v => Instant.FromDateTimeUtc(DateTime.SpecifyKind(v, DateTimeKind.Utc)));

        var localDateConverter = new ValueConverter<LocalDate?, DateTime?>(
            v => v.HasValue ? v.Value.ToDateTimeUnspecified() : (DateTime?)null,
            v => v.HasValue ? LocalDate.FromDateTime(v.Value) : (LocalDate?)null);

        modelBuilder.Entity<BaArtkey005>()
            .Property(e => e.Cpupdtms)
            .HasConversion(instantConverter);

        modelBuilder.Entity<BaArtkey005>()
            .Property(e => e.Dtendval)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaArtkey005>()
            .Property(e => e.Dtinival)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocume005>()
            .Property(e => e.Cpupdtms)
            .HasConversion(instantConverter);

        modelBuilder.Entity<BaDocume005>()
            .Property(e => e.Dodatcoc)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocume005>()
            .Property(e => e.Dodarcli)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocume005>()
            .Property(e => e.Dodatric)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocume005>()
            .Property(e => e.Dodatriv)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocume005>()
            .Property(e => e.Dofincom)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocume005>()
            .Property(e => e.Doinicom)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocumeM005>()
            .Property(e => e.Cpupdtms)
            .HasConversion(instantConverter);

        modelBuilder.Entity<BaDocumeM005>()
            .Property(e => e.Dodatreg)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocumeM005>()
            .Property(e => e.Dodatcon)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocumeM005>()
            .Property(e => e.Dodatdoc)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocumeM005>()
            .Property(e => e.Dodativa)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocumeM005>()
            .Property(e => e.Dodatope)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocumeM005>()
            .Property(e => e.Dodatpag)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocumeM005>()
            .Property(e => e.Dodatpla)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocumeM005>()
            .Property(e => e.Dodatret)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocumeM005>()
            .Property(e => e.Dodattra)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocumeM005>()
            .Property(e => e.Doordexp)
            .HasConversion(localDateConverter);

        modelBuilder.Entity<BaDocumeM005>()
            .Property(e => e.Dotmstamp)
            .HasConversion(instantConverter);

        modelBuilder.Entity<BaDocume005>()
            .Property(e => e.Dodatlim)
            .HasConversion(
            v => v.HasValue ? LocalDatePattern.Iso.Format(v.Value) : null,
            v => v != null ? LocalDatePattern.Iso.Parse(v).GetValueOrThrow() : (LocalDate?)null
        );

        modelBuilder.Entity<BaArtkey005>(entity =>
        {
            entity.HasKey(e => new { e.Kaflgart, e.Kaidguid }).HasName("PK_BA_ARTKEY005");

            entity.ToTable("ba_artkey005", tb => tb.HasTrigger("ba_artkey005_updtms"));

            entity.Property(e => e.Kaidguid).IsFixedLength();
            entity.Property(e => e.Cpccchk)
                .HasDefaultValue("qwertyuiop")
                .IsFixedLength();
            entity.Property(e => e.Cpupdtms).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Flactive).HasDefaultValue(1);
            entity.Property(e => e.Kacodsog).IsFixedLength();
            entity.Property(e => e.Kacodumi).IsFixedLength();
            entity.Property(e => e.Kaflbarp).HasDefaultValue(1);
            entity.Property(e => e.Kaflcomp).HasDefaultValue(1);
            entity.Property(e => e.Kafldocu).HasDefaultValue(1);
            entity.Property(e => e.Kaflgant).HasDefaultValue(0);
            entity.Property(e => e.Kaflgfase).HasDefaultValue(0);
            entity.Property(e => e.Kaflprin).HasDefaultValue(0);
            entity.Property(e => e.Kakeyart).IsFixedLength();
            entity.Property(e => e.Kanumdec).HasDefaultValue(0);
            entity.Property(e => e.Katipbar)
                .HasDefaultValue("   ")
                .IsFixedLength();
            entity.Property(e => e.Katipean).HasDefaultValue(0);
            entity.Property(e => e.Katipsog)
                .HasDefaultValue("AZI")
                .IsFixedLength();
        });

        modelBuilder.Entity<BaDocume005>(entity =>
        {
            entity.HasKey(e => new { e.Doserial, e.Cprownum }).HasName("PK_BA_DOCUME005");

            entity.ToTable("ba_docume005", tb => tb.HasTrigger("ba_docume005_updtms"));

            entity.Property(e => e.Doserial).IsFixedLength();
            entity.Property(e => e.Cpccchk)
                .HasDefaultValue("qwertyuiop")
                .IsFixedLength();
            entity.Property(e => e.Cproword).HasDefaultValue(0);
            entity.Property(e => e.Cpupdtms).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Doaggces).HasDefaultValue(0);
            entity.Property(e => e.Doarriva).HasDefaultValue(0m);
            entity.Property(e => e.Doasccom).HasDefaultValue(0);
            entity.Property(e => e.Doattcoa).IsFixedLength();
            entity.Property(e => e.Dobcalri).HasDefaultValue(0m);
            entity.Property(e => e.Dobcalrp).HasDefaultValue(0m);
            entity.Property(e => e.Docategory).HasDefaultValue(0m);
            entity.Property(e => e.Docauana).IsFixedLength();
            entity.Property(e => e.Docauma2row).IsFixedLength();
            entity.Property(e => e.Docaumarow).IsFixedLength();
            entity.Property(e => e.Docaupun).IsFixedLength();
            entity.Property(e => e.Docaures).IsFixedLength();
            entity.Property(e => e.Docdcadd).IsFixedLength();
            entity.Property(e => e.Docdccoa).IsFixedLength();
            entity.Property(e => e.Docodbun).IsFixedLength();
            entity.Property(e => e.Docodcid).IsFixedLength();
            entity.Property(e => e.Docodcii).IsFixedLength();
            entity.Property(e => e.Docodcio).IsFixedLength();
            entity.Property(e => e.Docodcoi).IsFixedLength();
            entity.Property(e => e.Docodcon).IsFixedLength();
            entity.Property(e => e.Docodcop).IsFixedLength();
            entity.Property(e => e.Docodcsa).IsFixedLength();
            entity.Property(e => e.Docodcsr).IsFixedLength();
            entity.Property(e => e.Docoddes).IsFixedLength();
            entity.Property(e => e.Docodiva).IsFixedLength();
            entity.Property(e => e.Docodkey).IsFixedLength();
            entity.Property(e => e.Docodma2row).IsFixedLength();
            entity.Property(e => e.Docodmarow).IsFixedLength();
            entity.Property(e => e.Docodora).IsFixedLength();
            entity.Property(e => e.Docomadd).IsFixedLength();
            entity.Property(e => e.Docomcoa).IsFixedLength();
            entity.Property(e => e.Doconman).HasDefaultValue(0);
            entity.Property(e => e.Docrelot).HasDefaultValue(0);
            entity.Property(e => e.Docremat).HasDefaultValue(0);
            entity.Property(e => e.Dodatint).HasDefaultValue(0);
            entity.Property(e => e.Dodbidpr).IsFixedLength();
            entity.Property(e => e.Dodbprog).HasDefaultValue(0);
            entity.Property(e => e.Dodbtoex).IsFixedLength();
            entity.Property(e => e.Dodtlpre).IsFixedLength();
            entity.Property(e => e.Dodtlprv).IsFixedLength();
            entity.Property(e => e.Doeqta2imp).HasDefaultValue(0m);
            entity.Property(e => e.Doeunimis).IsFixedLength();
            entity.Property(e => e.Doevaodl).HasDefaultValue(0m);
            entity.Property(e => e.Doflcapr).HasDefaultValue(0);
            entity.Property(e => e.Doflevaimport).HasDefaultValue(0);
            entity.Property(e => e.Doflfisc).HasDefaultValue(1);
            entity.Property(e => e.Doflgart).HasDefaultValue(1);
            entity.Property(e => e.Doflgenodx).HasDefaultValue(0);
            entity.Property(e => e.Doflgepr).HasDefaultValue(0);
            entity.Property(e => e.Doflgidroot).HasDefaultValue(0);
            entity.Property(e => e.Doflgodl)
                .HasDefaultValue(" ")
                .IsFixedLength();
            entity.Property(e => e.Doflgrif).HasDefaultValue(0);
            entity.Property(e => e.Doflgstp)
                .HasDefaultValue(" ")
                .IsFixedLength();
            entity.Property(e => e.Doflgsts)
                .HasDefaultValue(" ")
                .IsFixedLength();
            entity.Property(e => e.Dofllott).HasDefaultValue(0);
            entity.Property(e => e.Doflmatr).HasDefaultValue(0);
            entity.Property(e => e.Doflomag).HasDefaultValue(0);
            entity.Property(e => e.Doflprez).HasDefaultValue(0);
            entity.Property(e => e.Doflprom).HasDefaultValue(0);
            entity.Property(e => e.Doflprv1).HasDefaultValue(0);
            entity.Property(e => e.Doflprv2).HasDefaultValue(0);
            entity.Property(e => e.Doflripa).HasDefaultValue(0);
            entity.Property(e => e.Doflrval).HasDefaultValue(0);
            entity.Property(e => e.Doflscpa).HasDefaultValue(0);
            entity.Property(e => e.Doflsint).HasDefaultValue(0);
            entity.Property(e => e.Doflspac).HasDefaultValue(0);
            entity.Property(e => e.Doflspau).HasDefaultValue(0);
            entity.Property(e => e.Doflubic).HasDefaultValue(0);
            entity.Property(e => e.Doflvalo).HasDefaultValue(0);
            entity.Property(e => e.Dogenkit).HasDefaultValue(0);
            entity.Property(e => e.Dogenodx).IsFixedLength();
            entity.Property(e => e.Dogruspe).HasDefaultValue(0);
            entity.Property(e => e.Doidpland).IsFixedLength();
            entity.Property(e => e.Doimpadd).HasDefaultValue(0m);
            entity.Property(e => e.Doimpevp).HasDefaultValue(0m);
            entity.Property(e => e.Doimpevs).HasDefaultValue(0m);
            entity.Property(e => e.Doimplis).HasDefaultValue(0m);
            entity.Property(e => e.Doimplo2).HasDefaultValue(0m);
            entity.Property(e => e.Doimplor).HasDefaultValue(0m);
            entity.Property(e => e.Doimpne2).HasDefaultValue(0m);
            entity.Property(e => e.Doimpnet).HasDefaultValue(0m);
            entity.Property(e => e.Doimppr1).HasDefaultValue(0m);
            entity.Property(e => e.Doimppr2).HasDefaultValue(0m);
            entity.Property(e => e.Doimpsta).HasDefaultValue(0m);
            entity.Property(e => e.Doimpstp).HasDefaultValue(0m);
            entity.Property(e => e.Doimpsts).HasDefaultValue(0m);
            entity.Property(e => e.Doimptrc).HasDefaultValue(0m);
            entity.Property(e => e.Dointfor).HasDefaultValue(0);
            entity.Property(e => e.Doivade2).HasDefaultValue(0m);
            entity.Property(e => e.Doivadet).HasDefaultValue(0m);
            entity.Property(e => e.Doivain2).HasDefaultValue(0m);
            entity.Property(e => e.Doivaind).HasDefaultValue(0m);
            entity.Property(e => e.Dokeyart).IsFixedLength();
            entity.Property(e => e.Dokeyeff).IsFixedLength();
            entity.Property(e => e.Dokeygdo).IsFixedLength();
            entity.Property(e => e.Dolisadd).IsFixedLength();
            entity.Property(e => e.Dolisads).IsFixedLength();
            entity.Property(e => e.Dolispr1).IsFixedLength();
            entity.Property(e => e.Dolispr2).IsFixedLength();
            entity.Property(e => e.Dolispre).IsFixedLength();
            entity.Property(e => e.Dolissco).IsFixedLength();
            entity.Property(e => e.Donoriva).HasDefaultValue(0);
            entity.Property(e => e.Donotrel).IsFixedLength();
            entity.Property(e => e.Doodxsca).IsFixedLength();
            entity.Property(e => e.Dopardoc).IsFixedLength();
            entity.Property(e => e.Doperad1).HasDefaultValue(0m);
            entity.Property(e => e.Doperad2).HasDefaultValue(0m);
            entity.Property(e => e.Doperad3).HasDefaultValue(0m);
            entity.Property(e => e.Doperad4).HasDefaultValue(0m);
            entity.Property(e => e.Doperadd).HasDefaultValue(0m);
            entity.Property(e => e.Doperpr1).HasDefaultValue(0m);
            entity.Property(e => e.Doperpr2).HasDefaultValue(0m);
            entity.Property(e => e.Dopersc1).HasDefaultValue(0m);
            entity.Property(e => e.Dopersc2).HasDefaultValue(0m);
            entity.Property(e => e.Dopersc3).HasDefaultValue(0m);
            entity.Property(e => e.Dopersc4).HasDefaultValue(0m);
            entity.Property(e => e.Dopeslar).HasDefaultValue(0m);
            entity.Property(e => e.Dopesnar).HasDefaultValue(0m);
            entity.Property(e => e.Doppunti).HasDefaultValue(0m);
            entity.Property(e => e.Doprcoac).HasDefaultValue(0m);
            entity.Property(e => e.Dopresor).IsFixedLength();
            entity.Property(e => e.Doprezzo).HasDefaultValue(0m);
            entity.Property(e => e.Dopromot).IsFixedLength();
            entity.Property(e => e.Dopropre).IsFixedLength();
            entity.Property(e => e.Doprosco).IsFixedLength();
            entity.Property(e => e.Doqt1evp).HasDefaultValue(0m);
            entity.Property(e => e.Doqt1evs).HasDefaultValue(0m);
            entity.Property(e => e.Doqt1stp).HasDefaultValue(0m);
            entity.Property(e => e.Doqt1sts).HasDefaultValue(0m);
            entity.Property(e => e.Doqtaadd).HasDefaultValue(0m);
            entity.Property(e => e.Doqtamov).HasDefaultValue(0m);
            entity.Property(e => e.Doqtaum1).HasDefaultValue(0m);
            entity.Property(e => e.Doqtcoac).HasDefaultValue(0m);
            entity.Property(e => e.Doragsta).IsFixedLength();
            entity.Property(e => e.Dorcocom).HasDefaultValue(0);
            entity.Property(e => e.Dorifant).IsFixedLength();
            entity.Property(e => e.Dorifkit).HasDefaultValue(0);
            entity.Property(e => e.Dorifpre).HasDefaultValue(0);
            entity.Property(e => e.Doripsco).HasDefaultValue(1);
            entity.Property(e => e.Doripspe).HasDefaultValue(1);
            entity.Property(e => e.Doripsrv).HasDefaultValue(0);
            entity.Property(e => e.Dorispos).IsFixedLength();
            entity.Property(e => e.Dorowdic).HasDefaultValue(0);
            entity.Property(e => e.Doroweva).HasDefaultValue(0);
            entity.Property(e => e.Dorowodl).HasDefaultValue(0);
            entity.Property(e => e.Dorowodxs).HasDefaultValue(0);
            entity.Property(e => e.Dorowpos).HasDefaultValue(0);
            entity.Property(e => e.Dorowpre).HasDefaultValue(0);
            entity.Property(e => e.Dorowpri).HasDefaultValue(0);
            entity.Property(e => e.Doscopi2).HasDefaultValue(0m);
            entity.Property(e => e.Doscopic).HasDefaultValue(0m);
            entity.Property(e => e.Doscopie).HasDefaultValue(0m);
            entity.Property(e => e.Doscori2).HasDefaultValue(0m);
            entity.Property(e => e.Doscorig).HasDefaultValue(0m);
            entity.Property(e => e.Doscprom).HasDefaultValue(0);
            entity.Property(e => e.Doserdic).IsFixedLength();
            entity.Property(e => e.Doserevd).IsFixedLength();
            entity.Property(e => e.Doserocl).IsFixedLength();
            entity.Property(e => e.Doseroda).IsFixedLength();
            entity.Property(e => e.Doserodl).IsFixedLength();
            entity.Property(e => e.Doserpre).IsFixedLength();
            entity.Property(e => e.Doserpri).IsFixedLength();
            entity.Property(e => e.Doserqua).IsFixedLength();
            entity.Property(e => e.Dosnoimp).HasDefaultValue(0);
            entity.Property(e => e.Dosperi2).HasDefaultValue(0m);
            entity.Property(e => e.Dosperip).HasDefaultValue(0m);
            entity.Property(e => e.Dosrvri2).HasDefaultValue(0m);
            entity.Property(e => e.Dosrvrip).HasDefaultValue(0m);
            entity.Property(e => e.Dostgia2).HasDefaultValue(0);
            entity.Property(e => e.Dostgiac).HasDefaultValue(0);
            entity.Property(e => e.Dotippro).HasDefaultValue(0);
            entity.Property(e => e.Dotipval).HasDefaultValue(0);
            entity.Property(e => e.Dounimis).IsFixedLength();
            entity.Property(e => e.Dovalads).HasDefaultValue(0m);
            entity.Property(e => e.Dovalmag).HasDefaultValue(0m);
            entity.Property(e => e.Dovalori)
                .HasDefaultValue(" ")
                .IsFixedLength();
            entity.Property(e => e.Dovalpri)
                .HasDefaultValue(" ")
                .IsFixedLength();
            entity.Property(e => e.Dovalsco).HasDefaultValue(0m);
            entity.Property(e => e.Dovmagor).HasDefaultValue(0m);
            entity.Property(e => e.Dovocacc).IsFixedLength();
            entity.Property(e => e.Dovocadd).IsFixedLength();
            entity.Property(e => e.Dovoccoa).IsFixedLength();
            entity.Property(e => e.Dovoccop).IsFixedLength();

            entity.HasOne(d => d.DoserialNavigation).WithMany(p => p.BaDocume005s)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ba_docume005_1");

            entity.HasOne(d => d.BaArtkey005).WithMany(p => p.BaDocume005s).HasConstraintName("FK_ba_docume005_2");
        });

        modelBuilder.Entity<BaDocumeM005>(entity =>
        {
            entity.HasKey(e => e.Doserial).HasName("PK_BA_DOCUME_M005");

            entity.ToTable("ba_docume_m005", tb => tb.HasTrigger("ba_docume_m005_updtms"));

            entity.Property(e => e.Doserial).IsFixedLength();
            entity.Property(e => e.Cpccchk)
                .HasDefaultValue("qwertyuiop")
                .IsFixedLength();
            entity.Property(e => e.Cpupdtms).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Doagesup).IsFixedLength();
            entity.Property(e => e.Doaggpro).HasDefaultValue(0);
            entity.Property(e => e.Doalfpro).IsFixedLength();
            entity.Property(e => e.Doanacon).IsFixedLength();
            entity.Property(e => e.Doanafat).IsFixedLength();
            entity.Property(e => e.Doannpro).IsFixedLength();
            entity.Property(e => e.Doappinc).HasDefaultValue(1);
            entity.Property(e => e.Doattiva).IsFixedLength();
            entity.Property(e => e.Dobanclf).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.Dobannos).IsFixedLength();
            entity.Property(e => e.Dobusuni).IsFixedLength();
            entity.Property(e => e.Docaoval).HasDefaultValue(0m);
            entity.Property(e => e.Docaucon).IsFixedLength();
            entity.Property(e => e.Docauma2).IsFixedLength();
            entity.Property(e => e.Docaumag).IsFixedLength();
            entity.Property(e => e.Doccrpre).IsFixedLength();
            entity.Property(e => e.Dochkdib).IsFixedLength();
            entity.Property(e => e.Dochkocl).IsFixedLength();
            entity.Property(e => e.Docodage).IsFixedLength();
            entity.Property(e => e.Docodasp).IsFixedLength();
            entity.Property(e => e.Docodazi).IsFixedLength();
            entity.Property(e => e.Docodcau).IsFixedLength();
            entity.Property(e => e.Docoddip).IsFixedLength();
            entity.Property(e => e.Docodese).IsFixedLength();
            entity.Property(e => e.Docodfat).IsFixedLength();
            entity.Property(e => e.Docodlin).IsFixedLength();
            entity.Property(e => e.Docodlpz).IsFixedLength();
            entity.Property(e => e.Docodlsc).IsFixedLength();
            entity.Property(e => e.Docodma2).IsFixedLength();
            entity.Property(e => e.Docodmag).IsFixedLength();
            entity.Property(e => e.Docodpag).IsFixedLength();
            entity.Property(e => e.Docodpor).IsFixedLength();
            entity.Property(e => e.Docodrep).IsFixedLength();
            entity.Property(e => e.Docodsca).IsFixedLength();
            entity.Property(e => e.Docodsog).IsFixedLength();
            entity.Property(e => e.Docodspz).IsFixedLength();
            entity.Property(e => e.Docodter).IsFixedLength();
            entity.Property(e => e.Docodtra).IsFixedLength();
            entity.Property(e => e.Docoduff).IsFixedLength();
            entity.Property(e => e.Docodute).IsFixedLength();
            entity.Property(e => e.Docodval).IsFixedLength();
            entity.Property(e => e.Docodve2).IsFixedLength();
            entity.Property(e => e.Docodve3).IsFixedLength();
            entity.Property(e => e.Docodvet).IsFixedLength();
            entity.Property(e => e.Docommag).IsFixedLength();
            entity.Property(e => e.Docommar).IsFixedLength();
            entity.Property(e => e.Doconpre).HasDefaultValue(0);
            entity.Property(e => e.Docoupon).IsFixedLength();
            entity.Property(e => e.Docoupqta).HasDefaultValue(1);
            entity.Property(e => e.Docoupsign)
                .HasDefaultValue("+")
                .IsFixedLength();
            entity.Property(e => e.Docrecomp).IsFixedLength();
            entity.Property(e => e.Doddtrie).IsFixedLength();
            entity.Property(e => e.Dodibkey).IsFixedLength();
            entity.Property(e => e.Dodibrow).HasDefaultValue(0);
            entity.Property(e => e.Dodipcon).IsFixedLength();
            entity.Property(e => e.Dodipfat).IsFixedLength();
            entity.Property(e => e.Dodipsog).IsFixedLength();
            entity.Property(e => e.Dodisloc).HasDefaultValue(0m);
            entity.Property(e => e.Dofasedoc).IsFixedLength();
            entity.Property(e => e.Dofidcar).IsFixedLength();
            entity.Property(e => e.Dofilgen).HasDefaultValue(0);
            entity.Property(e => e.Doflaspe).HasDefaultValue(0);
            entity.Property(e => e.Doflccid).HasDefaultValue(2);
            entity.Property(e => e.Doflccom).HasDefaultValue(0);
            entity.Property(e => e.Doflcicl).IsFixedLength();
            entity.Property(e => e.Doflcoll).HasDefaultValue(0);
            entity.Property(e => e.Doflcont).HasDefaultValue(0);
            entity.Property(e => e.Dofldcor).HasDefaultValue(0);
            entity.Property(e => e.Doflevpa).HasDefaultValue(0);
            entity.Property(e => e.Doflgcalpro).HasDefaultValue(0);
            entity.Property(e => e.Doflgint).HasDefaultValue(0);
            entity.Property(e => e.Doflgiom).HasDefaultValue(0);
            entity.Property(e => e.Doflgpro).HasDefaultValue(1);
            entity.Property(e => e.Doflintr).HasDefaultValue(0);
            entity.Property(e => e.Doflivam).HasDefaultValue(0);
            entity.Property(e => e.Doflpick).HasDefaultValue(0);
            entity.Property(e => e.Doflprov).HasDefaultValue(1);
            entity.Property(e => e.Doflprva).HasDefaultValue(0);
            entity.Property(e => e.Doflrate).HasDefaultValue(0);
            entity.Property(e => e.Doflriva).HasDefaultValue(0);
            entity.Property(e => e.Doflscoc).HasDefaultValue(0);
            entity.Property(e => e.Doflscop).HasDefaultValue(0);
            entity.Property(e => e.Doflscor).HasDefaultValue(0);
            entity.Property(e => e.Doflsinc).HasDefaultValue(0);
            entity.Property(e => e.Doflstfa).HasDefaultValue(0);
            entity.Property(e => e.Dofltras).HasDefaultValue(0);
            entity.Property(e => e.Doforrip).HasDefaultValue(0);
            entity.Property(e => e.Dofzprev).HasDefaultValue(0);
            entity.Property(e => e.Dofzscco).HasDefaultValue(0);
            entity.Property(e => e.Dofzscfi).HasDefaultValue(0);
            entity.Property(e => e.Dofzspag).HasDefaultValue(0);
            entity.Property(e => e.Dogiofis).HasDefaultValue(0);
            entity.Property(e => e.Doidplanm).IsFixedLength();
            entity.Property(e => e.Doimpabb).HasDefaultValue(0m);
            entity.Property(e => e.Doimparr).HasDefaultValue(0m);
            entity.Property(e => e.Doimpass).HasDefaultValue(0m);
            entity.Property(e => e.Doimpbol).HasDefaultValue(0m);
            entity.Property(e => e.Doimpimb).HasDefaultValue(0m);
            entity.Property(e => e.Doimpinc).HasDefaultValue(0m);
            entity.Property(e => e.Doimpmin).HasDefaultValue(0m);
            entity.Property(e => e.Doimppre).HasDefaultValue(0m);
            entity.Property(e => e.Doimpspe).HasDefaultValue(0m);
            entity.Property(e => e.Doimptra).HasDefaultValue(0m);
            entity.Property(e => e.Doincart).IsFixedLength();
            entity.Property(e => e.Doivaese).IsFixedLength();
            entity.Property(e => e.Dolckgensca).HasDefaultValue(0);
            entity.Property(e => e.Dolinpro).IsFixedLength();
            entity.Property(e => e.Domincon).IsFixedLength();
            entity.Property(e => e.Domintra).IsFixedLength();
            entity.Property(e => e.Domodtra).IsFixedLength();
            entity.Property(e => e.Domotcre)
                .HasDefaultValue("   ")
                .IsFixedLength();
            entity.Property(e => e.Donotcor).IsFixedLength();
            entity.Property(e => e.Donumcol).HasDefaultValue(0m);
            entity.Property(e => e.Donumiv2).HasDefaultValue(0);
            entity.Property(e => e.Donumiva).HasDefaultValue(0);
            entity.Property(e => e.Donumpal).HasDefaultValue(0m);
            entity.Property(e => e.Donumpro).HasDefaultValue(0m);
            entity.Property(e => e.Donumrat).HasDefaultValue(0);
            entity.Property(e => e.Donumreg).HasDefaultValue(0m);
            entity.Property(e => e.Dooffcrm).HasDefaultValue(0);
            entity.Property(e => e.Dooldpre).HasDefaultValue(0m);
            entity.Property(e => e.Dooracon).IsFixedLength();
            entity.Property(e => e.Dooratra).IsFixedLength();
            entity.Property(e => e.Dopagcon).HasDefaultValue(0);
            entity.Property(e => e.Doparchf).HasDefaultValue(0);
            entity.Property(e => e.Doparmsp).IsFixedLength();
            entity.Property(e => e.Doparpre).IsFixedLength();
            entity.Property(e => e.Doparspe).IsFixedLength();
            entity.Property(e => e.Doperinc).HasDefaultValue(0m);
            entity.Property(e => e.Dopeslor).HasDefaultValue(0m);
            entity.Property(e => e.Dopesnet).HasDefaultValue(0m);
            entity.Property(e => e.Dopesrsp).HasDefaultValue(0m);
            entity.Property(e => e.Dopklnoc).HasDefaultValue(0);
            entity.Property(e => e.Doposcnt).IsFixedLength();
            entity.Property(e => e.Dopriori).HasDefaultValue(0);
            entity.Property(e => e.Doprznet).HasDefaultValue(0);
            entity.Property(e => e.Doqtawarn).HasDefaultValue(0);
            entity.Property(e => e.Dorifcon).IsFixedLength();
            entity.Property(e => e.Dorifent).IsFixedLength();
            entity.Property(e => e.Dorifscn).IsFixedLength();
            entity.Property(e => e.Dorowddr).HasDefaultValue(0);
            entity.Property(e => e.Dorowdib).HasDefaultValue(0);
            entity.Property(e => e.Dorowmsp).HasDefaultValue(0);
            entity.Property(e => e.Doruoag1).IsFixedLength();
            entity.Property(e => e.Doruoag2).IsFixedLength();
            entity.Property(e => e.Dosccart).IsFixedLength();
            entity.Property(e => e.Doscocas).HasDefaultValue(0m);
            entity.Property(e => e.Doscoco1).HasDefaultValue(0m);
            entity.Property(e => e.Doscoco2).HasDefaultValue(0m);
            entity.Property(e => e.Doscopag).HasDefaultValue(0m);
            entity.Property(e => e.Doscpart).IsFixedLength();
            entity.Property(e => e.Doserddr).IsFixedLength();
            entity.Property(e => e.Doserdib).IsFixedLength();
            entity.Property(e => e.Doserevt).IsFixedLength();
            entity.Property(e => e.Doserpro).IsFixedLength();
            entity.Property(e => e.Dosogfat).IsFixedLength();
            entity.Property(e => e.Dostatra).HasDefaultValue(0);
            entity.Property(e => e.Dostatus).HasDefaultValue(0);
            entity.Property(e => e.Dostorbol).HasDefaultValue(0m);
            entity.Property(e => e.Dostoreid).IsFixedLength();
            entity.Property(e => e.Dostorepos).IsFixedLength();
            entity.Property(e => e.Dotconta).IsFixedLength();
            entity.Property(e => e.Dotipage)
                .HasDefaultValue("AGE")
                .IsFixedLength();
            entity.Property(e => e.Dotipcol).IsFixedLength();
            entity.Property(e => e.Dotipdep).HasDefaultValue(0);
            entity.Property(e => e.Dotipdip).IsFixedLength();
            entity.Property(e => e.Dotipdoc)
                .HasDefaultValue("   ")
                .IsFixedLength();
            entity.Property(e => e.Dotipfat).IsFixedLength();
            entity.Property(e => e.Dotipiv2).IsFixedLength();
            entity.Property(e => e.Dotipiva).IsFixedLength();
            entity.Property(e => e.Dotipmag).HasDefaultValue(2);
            entity.Property(e => e.Dotippal).IsFixedLength();
            entity.Property(e => e.Dotipsog)
                .HasDefaultValue("   ")
                .IsFixedLength();
            entity.Property(e => e.Dotipspe)
                .HasDefaultValue("SPE")
                .IsFixedLength();
            entity.Property(e => e.Dotipter).IsFixedLength();
            entity.Property(e => e.Dotipvet)
                .HasDefaultValue("VET")
                .IsFixedLength();
            entity.Property(e => e.Dototimp).HasDefaultValue(0m);
            entity.Property(e => e.Dototiva).HasDefaultValue(0m);
            entity.Property(e => e.Dototvalcon).HasDefaultValue(0m);
            entity.Property(e => e.Dounist2).IsFixedLength();
            entity.Property(e => e.Dounisto).IsFixedLength();
            entity.Property(e => e.Doutient).HasDefaultValue(0);
            entity.Property(e => e.Dovalcas).HasDefaultValue(0m);
            entity.Property(e => e.Dovalcom).HasDefaultValue(0m);
            entity.Property(e => e.Dovalinc).HasDefaultValue(0m);
            entity.Property(e => e.Dovalmin).IsFixedLength();
            entity.Property(e => e.Dovalrat).HasDefaultValue(0m);
            entity.Property(e => e.Dovalrsp).HasDefaultValue(0m);
            entity.Property(e => e.Dovalspa).HasDefaultValue(0m);
            entity.Property(e => e.Dovolume).HasDefaultValue(0m);
        });

        modelBuilder.ApplyConfigurationsFromAssembly(typeof(FatturazioneDbContext).Assembly);

        base.OnModelCreating(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}