// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NodaTime;

namespace Fatturazione.Models;

[PrimaryKey("Kaflgart", "Kaidguid")]
[Table("ba_artkey005")]
[Index("Kacodric", Name = "ba_artkey0052")]
[Index("Kadescri", Name = "ba_artkey0053")]
public partial class BaArtkey005
{
    [Key]
    [Column("KAFLGART")]
    public int Kaflgart { get; set; }

    [Key]
    [Column("KAIDGUID")]
    [StringLength(10)]
    [Unicode(false)]
    public string Kaidguid { get; set; }

    [Column("KACODRIC")]
    [StringLength(50)]
    [Unicode(false)]
    public string Kacodric { get; set; }

    [Column("KADESCRI")]
    [StringLength(50)]
    [Unicode(false)]
    public string Kadescri { get; set; }

    [Column("KATIPSOG")]
    [StringLength(3)]
    [Unicode(false)]
    public string Katipsog { get; set; }

    [Column("KACODSOG")]
    [StringLength(16)]
    [Unicode(false)]
    public string Kacodsog { get; set; }

    [Column("KAKEYART")]
    [StringLength(10)]
    [Unicode(false)]
    public string Kakeyart { get; set; }

    [Column("KATIPBAR")]
    [StringLength(3)]
    [Unicode(false)]
    public string Katipbar { get; set; }

    [Column("KADESSUP", TypeName = "text")]
    public string Kadessup { get; set; }

    [Column("KACODUMI")]
    [StringLength(5)]
    [Unicode(false)]
    public string Kacodumi { get; set; }

    [Column("KAFLPRIN")]
    public int? Kaflprin { get; set; }

    [Column("FLACTIVE")]
    public int? Flactive { get; set; }

    [Column("DTINIVAL")]
    public LocalDate? Dtinival { get; set; }

    [Column("DTENDVAL")]
    public LocalDate? Dtendval { get; set; }

    [Column("KAFLDOCU")]
    public int? Kafldocu { get; set; }

    [Column("KAFLCOMP")]
    public int? Kaflcomp { get; set; }

    [Column("KAFLGANT")]
    public int? Kaflgant { get; set; }

    [Column("KAFLBARP")]
    public int? Kaflbarp { get; set; }

    [Column("KAFLGFASE")]
    public int? Kaflgfase { get; set; }

    [Column("cpupdtms", TypeName = "datetime")]
    public Instant? Cpupdtms { get; set; }

    [Column("KATIPEAN")]
    public int? Katipean { get; set; }

    [Column("KANUMDEC")]
    public int? Kanumdec { get; set; }

    [Column("cpccchk")]
    [StringLength(10)]
    [Unicode(false)]
    public string Cpccchk { get; set; }

    [InverseProperty("BaArtkey005")]
    public virtual ICollection<BaDocume005> BaDocume005s { get; set; } = new List<BaDocume005>();
}