// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using NodaTime;

namespace Fatturazione.Models;

[PrimaryKey("Doserial", "Cprownum")]
[Table("ba_docume005")]
[Index("Docodkey", Name = "ba_docume0052")]
[Index("Doserpre", Name = "ba_docume0053")]
[Index("Doserpri", Name = "ba_docume0054")]
[Index("Dodatcoc", Name = "ba_docume0055")]
[Index("Dokeyart", Name = "ba_docume0056")]
[Index("Doserodl", Name = "ba_docume0057")]
[Index("Doserocl", Name = "ba_docume0058")]
[Index("Doserdic", "Dorowdic", Name = "ba_docume0059")]
public partial class BaDocume005
{
    [Key]
    [Column("DOSERIAL")]
    [StringLength(10)]
    [Unicode(false)]
    public string Doserial { get; set; }

    [Key]
    [Column("CPROWNUM")]
    public int Cprownum { get; set; }

    [Column("CPROWORD")]
    public int? Cproword { get; set; }

    [Column("DOCODBUN")]
    [StringLength(10)]
    [Unicode(false)]
    public string Docodbun { get; set; }

    [Column("DODATRIC")]
    public LocalDate? Dodatric { get; set; }

    [Column("DODARCLI")]
    public LocalDate? Dodarcli { get; set; }

    [Column("DODATCOC")]
    public LocalDate? Dodatcoc { get; set; }

    [Column("DODATLIM")]
    public LocalDate? Dodatlim { get; set; }

    [Column("DOFLGART")]
    public int? Doflgart { get; set; }

    [Column("DOCODKEY")]
    [StringLength(10)]
    [Unicode(false)]
    public string Docodkey { get; set; }

    [Column("DOKEYART")]
    [StringLength(10)]
    [Unicode(false)]
    public string Dokeyart { get; set; }

    [Column("DODESART")]
    [StringLength(50)]
    [Unicode(false)]
    public string Dodesart { get; set; }

    [Column("DODESSUP", TypeName = "text")]
    public string Dodessup { get; set; }

    [Column("DOCODDES")]
    [StringLength(10)]
    [Unicode(false)]
    public string Docoddes { get; set; }

    [Column("DOFLSPAC")]
    public int? Doflspac { get; set; }

    [Column("DOFLRIPA")]
    public int? Doflripa { get; set; }

    [Column("DOUNIMIS")]
    [StringLength(5)]
    [Unicode(false)]
    public string Dounimis { get; set; }

    [Column("DOQTAMOV", TypeName = "decimal(20, 8)")]
    public decimal? Doqtamov { get; set; }

    [Column("DOQTAUM1", TypeName = "decimal(20, 8)")]
    public decimal? Doqtaum1 { get; set; }

    [Column("DOPREZZO", TypeName = "decimal(20, 5)")]
    public decimal? Doprezzo { get; set; }

    [Column("DOPERSC1", TypeName = "decimal(6, 2)")]
    public decimal? Dopersc1 { get; set; }

    [Column("DOPERSC2", TypeName = "decimal(6, 2)")]
    public decimal? Dopersc2 { get; set; }

    [Column("DOPERSC3", TypeName = "decimal(6, 2)")]
    public decimal? Dopersc3 { get; set; }

    [Column("DOPERSC4", TypeName = "decimal(6, 2)")]
    public decimal? Dopersc4 { get; set; }

    [Column("DOVALSCO", TypeName = "decimal(20, 5)")]
    public decimal? Dovalsco { get; set; }

    [Column("DOIMPLOR", TypeName = "decimal(20, 5)")]
    public decimal? Doimplor { get; set; }

    [Column("DOIMPLO2", TypeName = "decimal(20, 5)")]
    public decimal? Doimplo2 { get; set; }

    [Column("DOIMPNET", TypeName = "decimal(20, 5)")]
    public decimal? Doimpnet { get; set; }

    [Column("DOIMPNE2", TypeName = "decimal(20, 5)")]
    public decimal? Doimpne2 { get; set; }

    [Column("DOSCORIG", TypeName = "decimal(20, 5)")]
    public decimal? Doscorig { get; set; }

    [Column("DOSCORI2", TypeName = "decimal(20, 5)")]
    public decimal? Doscori2 { get; set; }

    [Column("DOSCOPIE", TypeName = "decimal(20, 5)")]
    public decimal? Doscopie { get; set; }

    [Column("DOSCOPI2", TypeName = "decimal(20, 5)")]
    public decimal? Doscopi2 { get; set; }

    [Column("DOSCOPIC", TypeName = "decimal(20, 5)")]
    public decimal? Doscopic { get; set; }

    [Column("DOSPERIP", TypeName = "decimal(20, 5)")]
    public decimal? Dosperip { get; set; }

    [Column("DOSPERI2", TypeName = "decimal(20, 5)")]
    public decimal? Dosperi2 { get; set; }

    [Column("DOSRVRIP", TypeName = "decimal(20, 5)")]
    public decimal? Dosrvrip { get; set; }

    [Column("DOSRVRI2", TypeName = "decimal(20, 5)")]
    public decimal? Dosrvri2 { get; set; }

    [Column("DOIVAIND", TypeName = "decimal(20, 5)")]
    public decimal? Doivaind { get; set; }

    [Column("DOIVAIN2", TypeName = "decimal(20, 5)")]
    public decimal? Doivain2 { get; set; }

    [Column("DOIVADET", TypeName = "decimal(20, 5)")]
    public decimal? Doivadet { get; set; }

    [Column("DOIVADE2", TypeName = "decimal(20, 5)")]
    public decimal? Doivade2 { get; set; }

    [Column("DOCODIVA")]
    [StringLength(10)]
    [Unicode(false)]
    public string Docodiva { get; set; }

    [Column("DOCODCON")]
    [StringLength(20)]
    [Unicode(false)]
    public string Docodcon { get; set; }

    [Column("DOCODCID")]
    [StringLength(20)]
    [Unicode(false)]
    public string Docodcid { get; set; }

    [Column("DOCODCII")]
    [StringLength(20)]
    [Unicode(false)]
    public string Docodcii { get; set; }

    [Column("DOCODCOI")]
    [StringLength(20)]
    [Unicode(false)]
    public string Docodcoi { get; set; }

    [Column("DOCODCIO")]
    [StringLength(20)]
    [Unicode(false)]
    public string Docodcio { get; set; }

    [Column("DOCODCSR")]
    [StringLength(20)]
    [Unicode(false)]
    public string Docodcsr { get; set; }

    [Column("DOCODCSA")]
    [StringLength(20)]
    [Unicode(false)]
    public string Docodcsa { get; set; }

    [Column("DOCODORA")]
    [StringLength(20)]
    [Unicode(false)]
    public string Docodora { get; set; }

    [Column("DOCODCOP")]
    [StringLength(20)]
    [Unicode(false)]
    public string Docodcop { get; set; }

    [Column("DOSERPRE")]
    [StringLength(10)]
    [Unicode(false)]
    public string Doserpre { get; set; }

    [Column("DOROWPRE")]
    public int? Dorowpre { get; set; }

    [Column("DOSERPRI")]
    [StringLength(10)]
    [Unicode(false)]
    public string Doserpri { get; set; }

    [Column("DOROWPRI")]
    public int? Dorowpri { get; set; }

    [Column("DOFLUBIC")]
    public int? Doflubic { get; set; }

    [Column("DOFLLOTT")]
    public int? Dofllott { get; set; }

    [Column("DOCRELOT")]
    public int? Docrelot { get; set; }

    [Column("DOFLMATR")]
    public int? Doflmatr { get; set; }

    [Column("DOCREMAT")]
    public int? Docremat { get; set; }

    [Column("DONOTREL")]
    [StringLength(10)]
    [Unicode(false)]
    public string Donotrel { get; set; }

    [Column("DOFLOMAG")]
    public int? Doflomag { get; set; }

    [Column("DOFLVALO")]
    public int? Doflvalo { get; set; }

    [Column("DOFLRVAL")]
    public int? Doflrval { get; set; }

    [Column("DOVALMAG", TypeName = "decimal(20, 5)")]
    public decimal? Dovalmag { get; set; }

    [Column("DOQT1EVS", TypeName = "decimal(20, 8)")]
    public decimal? Doqt1evs { get; set; }

    [Column("DOQT1EVP", TypeName = "decimal(20, 8)")]
    public decimal? Doqt1evp { get; set; }

    [Column("DOIMPEVS", TypeName = "decimal(20, 5)")]
    public decimal? Doimpevs { get; set; }

    [Column("DOIMPEVP", TypeName = "decimal(20, 5)")]
    public decimal? Doimpevp { get; set; }

    [Column("DOQT1STS", TypeName = "decimal(20, 8)")]
    public decimal? Doqt1sts { get; set; }

    [Column("DOQT1STP", TypeName = "decimal(20, 8)")]
    public decimal? Doqt1stp { get; set; }

    [Column("DOIMPSTS", TypeName = "decimal(20, 5)")]
    public decimal? Doimpsts { get; set; }

    [Column("DOIMPSTP", TypeName = "decimal(20, 5)")]
    public decimal? Doimpstp { get; set; }

    [Column("DOFLGSTS")]
    [StringLength(1)]
    [Unicode(false)]
    public string Doflgsts { get; set; }

    [Column("DOFLGSTP")]
    [StringLength(1)]
    [Unicode(false)]
    public string Doflgstp { get; set; }

    [Column("DOFLGRIF")]
    public int? Doflgrif { get; set; }

    [Column("DOARRIVA", TypeName = "decimal(20, 8)")]
    public decimal? Doarriva { get; set; }

    [Column("DOCAUANA")]
    [StringLength(10)]
    [Unicode(false)]
    public string Docauana { get; set; }

    [Column("DOVOCCOA")]
    [StringLength(20)]
    [Unicode(false)]
    public string Dovoccoa { get; set; }

    [Column("DOVOCACC")]
    [StringLength(20)]
    [Unicode(false)]
    public string Dovocacc { get; set; }

    [Column("DOVOCADD")]
    [StringLength(20)]
    [Unicode(false)]
    public string Dovocadd { get; set; }

    [Column("DOVOCCOP")]
    [StringLength(20)]
    [Unicode(false)]
    public string Dovoccop { get; set; }

    [Column("DOCDCCOA")]
    [StringLength(20)]
    [Unicode(false)]
    public string Docdccoa { get; set; }

    [Column("DOCDCADD")]
    [StringLength(20)]
    [Unicode(false)]
    public string Docdcadd { get; set; }

    [Column("DOCOMCOA")]
    [StringLength(20)]
    [Unicode(false)]
    public string Docomcoa { get; set; }

    [Column("DOCOMADD")]
    [StringLength(20)]
    [Unicode(false)]
    public string Docomadd { get; set; }

    [Column("DOATTCOA")]
    [StringLength(20)]
    [Unicode(false)]
    public string Doattcoa { get; set; }

    [Column("DOINICOM")]
    public LocalDate? Doinicom { get; set; }

    [Column("DOFINCOM")]
    public LocalDate? Dofincom { get; set; }

    [Column("DOIMPTRC", TypeName = "decimal(20, 5)")]
    public decimal? Doimptrc { get; set; }

    [Column("DOLISPRE")]
    [StringLength(20)]
    [Unicode(false)]
    public string Dolispre { get; set; }

    [Column("DOLISSCO")]
    [StringLength(20)]
    [Unicode(false)]
    public string Dolissco { get; set; }

    [Column("DOPROPRE")]
    [StringLength(20)]
    [Unicode(false)]
    public string Dopropre { get; set; }

    [Column("DOPROSCO")]
    [StringLength(20)]
    [Unicode(false)]
    public string Doprosco { get; set; }

    [Column("DOFLPROM")]
    public int? Doflprom { get; set; }

    [Column("DORIFKIT")]
    public int? Dorifkit { get; set; }

    [Column("DORIFPRE")]
    public int? Dorifpre { get; set; }

    [Column("DODATRIV")]
    public LocalDate? Dodatriv { get; set; }

    [Column("DOTIPVAL")]
    public int? Dotipval { get; set; }

    [Column("DOIMPPR1", TypeName = "decimal(20, 5)")]
    public decimal? Doimppr1 { get; set; }

    [Column("DOPERPR1", TypeName = "decimal(7, 2)")]
    public decimal? Doperpr1 { get; set; }

    [Column("DOLISPR1")]
    [StringLength(20)]
    [Unicode(false)]
    public string Dolispr1 { get; set; }

    [Column("DOIMPPR2", TypeName = "decimal(20, 5)")]
    public decimal? Doimppr2 { get; set; }

    [Column("DOPERPR2", TypeName = "decimal(7, 2)")]
    public decimal? Doperpr2 { get; set; }

    [Column("DOLISPR2")]
    [StringLength(20)]
    [Unicode(false)]
    public string Dolispr2 { get; set; }

    [Column("DOFLGEPR")]
    public int? Doflgepr { get; set; }

    [Column("DOQTAADD", TypeName = "decimal(20, 8)")]
    public decimal? Doqtaadd { get; set; }

    [Column("DOPERADD", TypeName = "decimal(7, 2)")]
    public decimal? Doperadd { get; set; }

    [Column("DOIMPADD", TypeName = "decimal(20, 5)")]
    public decimal? Doimpadd { get; set; }

    [Column("DOLISADD")]
    [StringLength(20)]
    [Unicode(false)]
    public string Dolisadd { get; set; }

    [Column("DOLISADS")]
    [StringLength(20)]
    [Unicode(false)]
    public string Dolisads { get; set; }

    [Column("DOPERAD1", TypeName = "decimal(6, 2)")]
    public decimal? Doperad1 { get; set; }

    [Column("DOPERAD2", TypeName = "decimal(6, 2)")]
    public decimal? Doperad2 { get; set; }

    [Column("DOPERAD3", TypeName = "decimal(6, 2)")]
    public decimal? Doperad3 { get; set; }

    [Column("DOPERAD4", TypeName = "decimal(6, 2)")]
    public decimal? Doperad4 { get; set; }

    [Column("DOVALADS", TypeName = "decimal(20, 5)")]
    public decimal? Dovalads { get; set; }

    [Column("DORIPSCO")]
    public int? Doripsco { get; set; }

    [Column("DORIPSPE")]
    public int? Doripspe { get; set; }

    [Column("DORIPSRV")]
    public int? Doripsrv { get; set; }

    [Column("DOVALPRI")]
    [StringLength(1)]
    [Unicode(false)]
    public string Dovalpri { get; set; }

    [Column("DOVALORI")]
    [StringLength(1)]
    [Unicode(false)]
    public string Dovalori { get; set; }

    [Column("DOVMAGOR", TypeName = "decimal(20, 5)")]
    public decimal? Dovmagor { get; set; }

    [Column("DORIFANT")]
    [StringLength(10)]
    [Unicode(false)]
    public string Dorifant { get; set; }

    [Column("DOFLFISC")]
    public int? Doflfisc { get; set; }

    [Column("DOFLSINT")]
    public int? Doflsint { get; set; }

    [Column("DOSTGIAC")]
    public int? Dostgiac { get; set; }

    [Column("DOSTGIA2")]
    public int? Dostgia2 { get; set; }

    [Column("DOSNOIMP")]
    public int? Dosnoimp { get; set; }

    [Column("DONORIVA")]
    public int? Donoriva { get; set; }

    [Column("DOFLCAPR")]
    public int? Doflcapr { get; set; }

    [Column("DOIMPLIS", TypeName = "decimal(20, 5)")]
    public decimal? Doimplis { get; set; }

    [Column("DOFLSPAU")]
    public int? Doflspau { get; set; }

    [Column("DOPARDOC")]
    [StringLength(10)]
    [Unicode(false)]
    public string Dopardoc { get; set; }

    [Column("DOAGGCES")]
    public int? Doaggces { get; set; }

    [Column("DOBCALRI", TypeName = "decimal(20, 8)")]
    public decimal? Dobcalri { get; set; }

    [Column("DOBCALRP", TypeName = "decimal(20, 8)")]
    public decimal? Dobcalrp { get; set; }

    [Column("DOGRUSPE")]
    public int? Dogruspe { get; set; }

    [Column("DOFLPREZ")]
    public int? Doflprez { get; set; }

    [Column("DOCATEGORY", TypeName = "decimal(10, 0)")]
    public decimal? Docategory { get; set; }

    [Column("DODTLPRE")]
    [StringLength(10)]
    [Unicode(false)]
    public string Dodtlpre { get; set; }

    [Column("DODTLPRV")]
    [StringLength(10)]
    [Unicode(false)]
    public string Dodtlprv { get; set; }

    [Column("DORCOCOM")]
    public int? Dorcocom { get; set; }

    [Column("DODATINT")]
    public int? Dodatint { get; set; }

    [Column("DODETEFF", TypeName = "text")]
    public string Dodeteff { get; set; }

    [Column("DOASCCOM")]
    public int? Doasccom { get; set; }

    [Column("DOQTCOAC", TypeName = "decimal(20, 8)")]
    public decimal? Doqtcoac { get; set; }

    [Column("DOPRCOAC", TypeName = "decimal(6, 2)")]
    public decimal? Doprcoac { get; set; }

    [Column("DOSERODL")]
    [StringLength(10)]
    [Unicode(false)]
    public string Doserodl { get; set; }

    [Column("DOROWODL")]
    public int? Dorowodl { get; set; }

    [Column("DOEVAODL", TypeName = "decimal(20, 8)")]
    public decimal? Doevaodl { get; set; }

    [Column("DOFLGODL")]
    [StringLength(1)]
    [Unicode(false)]
    public string Doflgodl { get; set; }

    [Column("DOINTFOR")]
    public int? Dointfor { get; set; }

    [Column("DODBTOEX")]
    [StringLength(10)]
    [Unicode(false)]
    public string Dodbtoex { get; set; }

    [Column("DODBPROG")]
    public int? Dodbprog { get; set; }

    [Column("DODBIDPR")]
    [StringLength(5)]
    [Unicode(false)]
    public string Dodbidpr { get; set; }

    [Column("DOCAURES")]
    [StringLength(10)]
    [Unicode(false)]
    public string Docaures { get; set; }

    [Column("DOIMPSTA", TypeName = "decimal(20, 5)")]
    public decimal? Doimpsta { get; set; }

    [Column("DOSERODA")]
    [StringLength(10)]
    [Unicode(false)]
    public string Doseroda { get; set; }

    [Column("DOSEROCL")]
    [StringLength(10)]
    [Unicode(false)]
    public string Doserocl { get; set; }

    [Column("DORAGSTA")]
    [StringLength(3)]
    [Unicode(false)]
    public string Doragsta { get; set; }

    [Column("DOFLSCPA")]
    public int? Doflscpa { get; set; }

    [Column("DOGENKIT")]
    public int? Dogenkit { get; set; }

    [Column("cpupdtms", TypeName = "datetime")]
    public Instant? Cpupdtms { get; set; }

    [Column("DOODXSCA")]
    [StringLength(10)]
    [Unicode(false)]
    public string Doodxsca { get; set; }

    [Column("DOROWODXS")]
    public int? Dorowodxs { get; set; }

    [Column("DOPRESOR")]
    [StringLength(3)]
    [Unicode(false)]
    public string Dopresor { get; set; }

    [Column("DOSERDIC")]
    [StringLength(10)]
    [Unicode(false)]
    public string Doserdic { get; set; }

    [Column("DOROWDIC")]
    public int? Dorowdic { get; set; }

    [Column("DORISPOS")]
    [StringLength(10)]
    [Unicode(false)]
    public string Dorispos { get; set; }

    [Column("DOROWPOS")]
    public int? Dorowpos { get; set; }

    [Column("DOKEYEFF")]
    [StringLength(10)]
    [Unicode(false)]
    public string Dokeyeff { get; set; }

    [Column("DOPROMOT")]
    [StringLength(10)]
    [Unicode(false)]
    public string Dopromot { get; set; }

    [Column("DOPESLAR", TypeName = "decimal(20, 8)")]
    public decimal? Dopeslar { get; set; }

    [Column("DOPESNAR", TypeName = "decimal(20, 8)")]
    public decimal? Dopesnar { get; set; }

    [Column("DOCONMAN")]
    public int? Doconman { get; set; }

    [Column("DOFLPRV1")]
    public int? Doflprv1 { get; set; }

    [Column("DOFLPRV2")]
    public int? Doflprv2 { get; set; }

    [Column("DOSERQUA")]
    [StringLength(10)]
    [Unicode(false)]
    public string Doserqua { get; set; }

    [Column("DOSEREVD")]
    [StringLength(10)]
    [Unicode(false)]
    public string Doserevd { get; set; }

    [Column("DOROWEVA")]
    public int? Doroweva { get; set; }

    [Column("DOEQTA2IMP", TypeName = "decimal(20, 8)")]
    public decimal? Doeqta2imp { get; set; }

    [Column("DOEUNIMIS")]
    [StringLength(5)]
    [Unicode(false)]
    public string Doeunimis { get; set; }

    [Column("DOIDPLAND")]
    [StringLength(10)]
    [Unicode(false)]
    public string Doidpland { get; set; }

    [Column("DOPPUNTI", TypeName = "decimal(10, 0)")]
    public decimal? Doppunti { get; set; }

    [Column("DOCAUPUN")]
    [StringLength(10)]
    [Unicode(false)]
    public string Docaupun { get; set; }

    [Column("DOTIPPRO")]
    public int? Dotippro { get; set; }

    [Column("DOFLGIDROOT")]
    public int? Doflgidroot { get; set; }

    [Column("DOSCPROM")]
    public int? Doscprom { get; set; }

    [Column("DOGENODX")]
    [StringLength(10)]
    [Unicode(false)]
    public string Dogenodx { get; set; }

    [Column("DOFLGENODX")]
    public int? Doflgenodx { get; set; }

    [Column("cpccchk")]
    [StringLength(10)]
    [Unicode(false)]
    public string Cpccchk { get; set; }

    [Column("DOCAUMAROW")]
    [StringLength(10)]
    [Unicode(false)]
    public string Docaumarow { get; set; }

    [Column("DOCAUMA2ROW")]
    [StringLength(10)]
    [Unicode(false)]
    public string Docauma2row { get; set; }

    [Column("DOCODMAROW")]
    [StringLength(10)]
    [Unicode(false)]
    public string Docodmarow { get; set; }

    [Column("DOCODMA2ROW")]
    [StringLength(10)]
    [Unicode(false)]
    public string Docodma2row { get; set; }

    [Column("DOKEYGDO")]
    [StringLength(20)]
    [Unicode(false)]
    public string Dokeygdo { get; set; }

    [Column("DOFLEVAIMPORT")]
    public int? Doflevaimport { get; set; }

    [ForeignKey("Doflgart, Docodkey")]
    [InverseProperty("BaDocume005s")]
    public virtual BaArtkey005 BaArtkey005 { get; set; }

    [ForeignKey("Doserial")]
    [InverseProperty("BaDocume005s")]
    public virtual BaDocumeM005 DoserialNavigation { get; set; }
}