namespace Fatturazione.Models
{
    public class FatturaGenerateDTO
    {
        public TestataFatturaDTO Testata {  get; set; }
        public List<RigaFatturaDTO> Righe { get; set; }
    }

    public class TestataFatturazioneDTO 
    {
        public string Numfac { get; set; }
        public DateTime Fentrega { get; set; }
        public decimal Baseimp1 { get; set; }
        public decimal Sumnetos { get; set; }
        public decimal Descuen { get; set; }
        public string Vendedor { get; set; }
        public string Emisor { get; set; }
        public string Cobrador { get; set; }
        public string Comprado { get; set; }
        public string Depto { get; set; }
        public string Receptor { get; set; }
        public string Cliente { get; set; }
        public string Pagador { get; set; }
        public string Pedido { get; set; }
        public DateTime Fecha { get; set; }
        public string Nodo { get; set; }
        public string Funcion { get; set; }
        public string Rsocial { get; set; }
        public string Calle { get; set; }
        public string Ciudad { get; set; }
        public string Cp { get; set; }
        public string Nif { get; set; }
        public string Razon { get; set; }
        public string Albaran { get; set; }
        public string Contrato { get; set; }
        public string Nfacsus { get; set; }
        public string Fpag { get; set; }
        public string Divisa { get; set; }
        public decimal Sumbruto { get; set; }
        public decimal Cargos { get; set; }
        public string Tipoimp1 { get; set; }
        public decimal Tasaimp1 { get; set; }
        public decimal Impimp1 { get; set; }
        public decimal Basimpfa { get; set; }
        public decimal Totimp { get; set; }
        public decimal Total { get; set; }
        public string Vto1 { get; set; }
        public decimal Impvto1 { get; set; }
        public string Vto2 { get; set; }
        public decimal Impvto2 { get; set; }
        public string Vto3 { get; set; }
        public decimal Impvto3 { get; set; }
        public string Taverde { get; set; }
        public string Ersocial { get; set; }
        public string Ecalle { get; set; }
        public string Epoblac { get; set; }
        public string Ecp { get; set; }
        public string Enif { get; set; }
        public string Ermerca { get; set; }
        public string Notac { get; set; }
        public string Numrel { get; set; }
        public string Recogida { get; set; }
        public string Destino { get; set; }
        public DateTime Fechaefe { get; set; }
        public string Nconfrec { get; set; }
        public string Nidenticket { get; set; }
        public string Contacto { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Codprov { get; set; }
        public DateTime Fecalb { get; set; }
        public string Normexen1 { get; set; }
        public string Normexen2 { get; set; }
        public string Normexen3 { get; set; }
        public string Normexen4 { get; set; }
        public string Normexen5 { get; set; }
        public string Normexen6 { get; set; }
        public DateTime Fechadoc { get; set; }
        public string Refpago { get; set; }
        public string Origen { get; set; }
        public string Nifii { get; set; }
        public string Nifpe { get; set; }
        public string Nifiv { get; set; }
        public string Nifpr { get; set; }
        public string Nifsu { get; set; }
        public string Nummovi { get; set; }
        public string Numincor { get; set; }
        public decimal Impincor { get; set; }
        public DateTime Fentmer { get; set; }
        public DateTime Femimen { get; set; }
        public string Nummen { get; set; }
        public decimal Percfac { get; set; }
        public string Fpedido { get; set; }
        public string Codaprob { get; set; }
        public string Numdevol { get; set; }
        public DateTime Fnumdevol { get; set; }
        public string Notifdevol { get; set; }
        public DateTime Fnotifdevol { get; set; }
        public string Sedesoc { get; set; }
        public string Buque { get; set; }
        public DateTime Fembarque { get; set; }
        public string Forwarder { get; set; }
        public string Rrsocial { get; set; }
        public string Rcalle { get; set; }
        public string Rciudad { get; set; }
        public string Rcp { get; set; }
        public string Agenenif { get; set; }
        public string Ecapsocial { get; set; }
        public string Lugcarga { get; set; }
        public DateTime Fcarga { get; set; }
        public string Lugdescarga { get; set; }
        public string Matricula { get; set; }
        public string Numven { get; set; }
        public string Cpext { get; set; }
        public string Ecpext { get; set; }
        public DateTime Fecfacsus { get; set; }
        public string Epais { get; set; }
        public string Relvto { get; set; }
        public int Diasvto { get; set; }
        public decimal Porcvto { get; set; }
        public string Tipoimpdes1 { get; set; }
        public decimal Tasaimpdes1 { get; set; }
        public decimal Impimpdes1 { get; set; }
        public string Baseimpdes1 { get; set; }
        public string Tipoimpdes2 { get; set; }
        public decimal Tasaimpdes2 { get; set; }
        public decimal Impimpdes2 { get; set; }
        public string Baseimpdes2 { get; set; }
        public string Tipoimpdes3 { get; set; }
        public decimal Tasaimpdes3 { get; set; }
        public decimal Impimpdes3 { get; set; }
        public string Baseimpdes3 { get; set; }
        public string Tipoimpdes4 { get; set; }
        public decimal Tasaimpdes4 { get; set; }
        public decimal Impimpdes4 { get; set; }
        public string Baseimpdes4 { get; set; }
        public string Tipoimpdes5 { get; set; }
        public decimal Tasaimpdes5 { get; set; }
        public decimal Impimpdes5 { get; set; }
        public string Baseimpdes5 { get; set; }
        public string Paisby { get; set; }
        public string Regcritcaja { get; set; }
        public string Taxcat { get; set; }
        public string Taxcat1 { get; set; }
        public string Taxcat2 { get; set; }
        public string Taxcat3 { get; set; }
        public string Taxcat4 { get; set; }
        public string Taxcat5 { get; set; }
        public string Taxcat6 { get; set; }
        public string Autor { get; set; }
        public string Titulo { get; set; }
    }

    public class RigaFatturazioneDTO
    {
        public string NumFac { get; set; }
        public int NumLin { get; set; }
        public string RefEan { get; set; }
        public string RefCli { get; set; }
        public string RefPro { get; set; }
        public string VP { get; set; }
        public string DUN14 { get; set; }
        public string Desc { get; set; }
        public decimal CFact { get; set; }
        public string Cent { get; set; }
        public string UMedida { get; set; }
        public decimal PrecioB { get; set; }
        public decimal PrecioN { get; set; }
        public string TipoImp1 { get; set; }
        public decimal TasaImp1 { get; set; }
        public decimal ImpTasa1 { get; set; }
        public string TipoImp2 { get; set; }
        public decimal TasaImp2 { get; set; }
        public decimal ImpTasa2 { get; set; }
        public string TipoImp3 { get; set; }
        public decimal TasaImp3 { get; set; }
        public decimal ImpTasa3 { get; set; }
        public string Calif1 { get; set; }
        public int Secuen1 { get; set; }
        public string Tipo1 { get; set; }
        public decimal Porcen1 { get; set; }
        public decimal ImpDto1 { get; set; }
        public string Calif2 { get; set; }
        public int Secuen2 { get; set; }
        public decimal Porcen2 { get; set; }
        public decimal ImpDto2 { get; set; }
        public string Calif3 { get; set; }
        public int Secuen3 { get; set; }
        public string Tipo3 { get; set; }
        public decimal Porcen3 { get; set; }
        public decimal ImpDto3 { get; set; }
        public string Calif4 { get; set; }
        public int Secuen4 { get; set; }
        public string Tipo4 { get; set; }
        public decimal Porcen4 { get; set; }
        public decimal ImpDto4 { get; set; }
        public string CBoni { get; set; }
        public decimal Neto { get; set; }
        public string PVerde { get; set; }
        public string Pedido { get; set; }
        public string Albaran { get; set; }
        public string Lote { get; set; }
        public DateTime FCarga { get; set; }
        public DateTime FEntrega { get; set; }
        public string Matricula { get; set; }
        public string TipArt { get; set; }
        public decimal CantDev { get; set; }
        public string Seccion { get; set; }
        public string NIdenTicket { get; set; }
        public decimal Bruto { get; set; }
        public DateTime FecAlb { get; set; }
        public string Autor { get; set; }
        public string Titolo { get; set; }
        public string Cuexp { get; set; }
        public string UMCuexp { get; set; }
        public DateTime FechaEfe { get; set; }
        public string Categoria { get; set; }
        public string SubLin { get; set; }
        public string NormExen1 { get; set; }
        public string NormExen2 { get; set; }
        public string NormExen3 { get; set; }
        public string TipoEmbalaje { get; set; }
        public int NumLinPed { get; set; }
        public string GrpLinCom { get; set; }
        public int PosLinInt { get; set; }
        public DateTime FPedido { get; set; }
        public string UBasePn { get; set; }
        public string UMedPn { get; set; }
        public string TaxCat { get; set; }
        public string Modelo { get; set; }
        public string Color { get; set; }
        public decimal ImpRappel { get; set; }
        public decimal PrecioDis { get; set; }
        public decimal Peso { get; set; }
        public string UPeso { get; set; }
        public string NumEmb { get; set; }
        public int NumSubLin { get; set; }
        public string DescTipo1 { get; set; }
        public string DescTipo2 { get; set; }
        public string DescTipo3 { get; set; }
        public string DescTipo4 { get; set; }
        public decimal KilosPlas { get; set; }
        public string RegProdProducto { get; set; }
    }
}
